Internal Server Error: /edit_operation/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view desk.views.edit_operation didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /edit_operation/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view desk.views.edit_operation didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /edit_operation/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view desk.views.edit_operation didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /edit_operation/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view desk.views.edit_operation didn't return an HttpResponse object. It returned None instead.
